name:                usocomp
version:             0.1.0.0
github:              "githubuser/usocomp"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/usocomp#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- mtl
- containers
- text
- primitive
- megaparsec
- parser-combinators
- transformers

default-extensions:
- StrictData
- DataKinds
- NoImplicitPrelude
- OverloadedStrings
- GADTs
- LambdaCase
- TypeAbstractions

language: GHC2024

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

flags:
  web:
    default: false
    manual: true

executables:
  slangc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - usocomp
    - directory
    when:
      condition: "flag(web)"
      then:
        buildable: false
      else:
        buildable: true
  slangcweb:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -no-hs-main
    - -optl-Wl,--export=hs_init,--export=compile
    - -optl-mexec-model=reactor
    dependencies:
    - usocomp
    - ghc-experimental
    when:
      condition: "flag(web)"
      then:
        buildable: true
      else:
        buildable: false

tests:
  usocomp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - usocomp
    - hspec
